[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
port = 8501
address = "localhost"
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[runner]
magicEnabled = true
installTracer = true
fixMatplotlib = true

[client]
showErrorDetails = true
toolbarMode = "auto"
